version: '3.2'

services:
  server:
    container_name: server
    build:
      dockerfile: .docker/Dockerfile
      context: .
    networks:
      - scribble-network
    volumes:
      - ./app:/code/app
      - ./public:/code/public
    depends_on:
      - proxy
    ports:
      - 8000:80

  proxy:
    container_name: proxy
    image: nginx:1.25.3-bookworm
    networks:
      - scribble-network
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/logs:/var/log/nginx
      - ./public:/usr/share/nginx/html
      # - ./.docker/nginx:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: curl --fail http://localhost/status || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

networks:
  scribble-network:
    external: true